# Generated by Django 5.1.3 on 2024-11-19 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANÚNCIO/PUBLICIDADE', 'Anúncio/Publicidade'), ('AO VIVO E CHAMADA', 'Ao Vivo e Chamada'), ('ARTIGO', 'Artigo'), ('CARTA/EMAIL', 'Carta/Email'), ('CHAMADA DE CAPA', 'Chamada de Capa'), ('CHARGE', 'Charge'), ('CINEMA', 'Cinema'), ('COLUNA', 'Coluna'), ('CRÔNICA', 'Crônica'), ('CURTAS', 'Curtas'), ('DEBATE', 'Debate'), ('EDITAL', 'Edital'), ('EDITORIAL', 'Editorial'), ('ENTREVISTA', 'Entrevista'), ('ESCALADA', 'Escalada'), ('FEED', 'Feed'), ('IGTV', 'IGTV'), ('INSERÇÃO ELEITORAL', 'Inserção Eleitoral'), ('MATÉRIA', 'Matéria'), ('MATÉRIA COM CHAMADA', 'Matéria com chamada'), ('NOTA', 'Nota'), ('PROGRAMA ELEITORAL', 'Programa eleitoral'), ('Reportagem', 'Reportagem'), ('Stories', 'Stories')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editorias', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('data_publicacao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('link_noticia', models.URLField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('resumo', models.CharField(blank=True, max_length=500, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('a4', models.FileField(blank=True, null=True, upload_to='a4/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('printscreen', models.ImageField(blank=True, null=True, upload_to='printscreen/')),
                ('editoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.editoria')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='veiculos.veiculo')),
                ('tipo_noticia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.tipodenoticia')),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
