# Generated by Django 5.1.3 on 2024-11-19 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj_cpf', models.CharField(max_length=14, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=9)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('contato_1', models.CharField(max_length=20)),
                ('contato_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ContatoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('contato', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('contato', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GestorContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('contato', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('objeto', models.TextField()),
                ('informacoes_adicionais', models.TextField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20)),
                ('vigencia', models.DateField()),
                ('contrato_assinado', models.BooleanField(default=False)),
                ('cobranca', models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], default='Mensal', max_length=20)),
                ('prorrogacao', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dia_pagamento', models.IntegerField(blank=True, help_text='Escolha o dia do mês (1-31) para pagamento.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('envio_nf', models.BooleanField(default=False)),
                ('dia_emissao_nf', models.IntegerField(blank=True, help_text='Escolha o dia do mês (1-31) para emissão da NF.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('produtos', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='contratos/documentos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente')),
                ('contato_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.contatofinanceiro')),
                ('contato_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.contatooperacional')),
                ('empresa_contratada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.empresa')),
                ('gestor_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.gestorcontrato')),
            ],
            options={
                'ordering': ['cliente', 'numero'],
            },
        ),
    ]
